version: '3'
services:
  ride:
    build: ./ride/app/
    command: python main_rides.py
    restart: always
    ports:
      - "8000:8000"
  user:
    build: ./user/app/
    command: python main_user.py
    restart: always
    ports:
      - "8080:8080"
